ALTER TABLE settings ADD COLUMN IF NOT EXISTS tax_mode VARCHAR(20) DEFAULT 'kleinunternehmer';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(5,2) DEFAULT 19.00;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS tax_id VARCHAR(50);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS vat_id VARCHAR(50);
